-- Settings
local opt = vim.opt
opt.timeoutlen = 200
opt.ttimeoutlen=0
opt.guicursor = "n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20"
opt.shiftwidth = 4
opt.scrolloff = 4
opt.termguicolors = true
opt.smartindent = true
opt.wrap = true
opt.updatetime = 50
opt.list = true
-- opt.cursorline = true
opt.tabstop = 4
opt.expandtab = true
opt.softtabstop = 4
opt.splitbelow = true
opt.splitright = true
opt.incsearch = true
opt.hlsearch = true
opt.ignorecase = true
opt.smartcase = true
opt.undofile = true
opt.undodir = vim.fn.stdpath("state") .. "/undo"
