# -*- mode: ruby -*-
# vi: set ft=ruby :

# vagrant plugin install vagrant-disksize
Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"
  config.disksize.size = '90GB'
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end
end

