[mgr]
prepend_keymap = [
{ on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
{ on = "z",   run = "plugin zoxide",       desc = "Jump to a directory via zoxide"  },
{ on = "Z",   run = "plugin fzf",      desc = "Jump to a file/directory via fzf"  },
]

