[window.padding]
x = 4
y = 4

[env]
TERM = "alacritty"

[font]
size = 14.0
[font.normal]
family = "MapleMono NF CN"
style = "Normal"

[font.bold]
family = "MapleMono NF CN" 
style = "Bold"

[font.italic]
family = "MapleMono NF CN"
style = "Italic"

[font.bold_italic]
family = "MapleMono NF CN"
style = "Bold Italic"

[cursor]
style = "Block"
blink_interval = 0
unfocused_hollow = true

[mouse]
hide_when_typing = false

[colors]
primary = { background = "#272727" }

[[keyboard.bindings]]
key = "Return"
mods = "Control | Shift"
action = "SpawnNewInstance"

