[window.padding]
x = 6
y = 6

[env]
TERM = "alacritty"

[font]
size = 14.0

[font.normal]
family = "JetBrains Mono Nerd Font"

[font.bold]
family = "JetBrains Mono Nerd Font"

[font.italic]
family = "JetBrains Mono Nerd Font"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"

[cursor]
style = "Block"
blink_interval = 0
unfocused_hollow = true

[mouse]
hide_when_typing = false

[colors]
primary = { background = "#272727" }

[[keyboard.bindings]]
key = "Return"
mods = "Control | Shift"
action = "SpawnNewInstance"

