
window.opacity = 0.76
[general]
live_config_reload = true
# import = ["/home/arch/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
import = ["/home/arch/.config/alacritty/theme/gruvbox-material-alacritty.toml"]


[colors.primary]
background = "#1d2021"
foreground = "#d4be98"

[font]
size = 14

[font.normal]
family = "Jetbrains Mono Nerd Font"
style = "Regular"

[terminal]

# [[keyboard.bindings]]
# action = "SpawnNewInstance"
# key = "Return"
# mods = "Control|Shift"

[terminal.shell]
program = "/usr/bin/zsh"

[window.padding]
x = 20
y = 20
